/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RequestsIndexRouteImport } from './routes/requests/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminTeamsIndexRouteImport } from './routes/admin/teams/index'
import { Route as AdminRequestsIndexRouteImport } from './routes/admin/requests/index'
import { Route as AdminProfileRequestsIndexRouteImport } from './routes/admin/profile-requests/index'
import { Route as AdminEmailTemplatesIndexRouteImport } from './routes/admin/email-templates/index'
import { Route as AdminCompetenciesIndexRouteImport } from './routes/admin/competencies/index'
import { Route as AdminTeamsAnalyticsRouteImport } from './routes/admin/teams/analytics'
import { Route as AdminTeamsTeamIdRouteImport } from './routes/admin/teams/$teamId'
import { Route as AdminCompetenciesRequirementsIndexRouteImport } from './routes/admin/competencies/requirements/index'
import { Route as AdminCompetenciesCyclesIndexRouteImport } from './routes/admin/competencies/cycles/index'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIndexRoute = RequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamsIndexRoute = AdminTeamsIndexRouteImport.update({
  id: '/admin/teams/',
  path: '/admin/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRequestsIndexRoute = AdminRequestsIndexRouteImport.update({
  id: '/admin/requests/',
  path: '/admin/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRequestsIndexRoute =
  AdminProfileRequestsIndexRouteImport.update({
    id: '/admin/profile-requests/',
    path: '/admin/profile-requests/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminEmailTemplatesIndexRoute =
  AdminEmailTemplatesIndexRouteImport.update({
    id: '/admin/email-templates/',
    path: '/admin/email-templates/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCompetenciesIndexRoute = AdminCompetenciesIndexRouteImport.update({
  id: '/admin/competencies/',
  path: '/admin/competencies/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamsAnalyticsRoute = AdminTeamsAnalyticsRouteImport.update({
  id: '/admin/teams/analytics',
  path: '/admin/teams/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamsTeamIdRoute = AdminTeamsTeamIdRouteImport.update({
  id: '/admin/teams/$teamId',
  path: '/admin/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCompetenciesRequirementsIndexRoute =
  AdminCompetenciesRequirementsIndexRouteImport.update({
    id: '/admin/competencies/requirements/',
    path: '/admin/competencies/requirements/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCompetenciesCyclesIndexRoute =
  AdminCompetenciesCyclesIndexRouteImport.update({
    id: '/admin/competencies/cycles/',
    path: '/admin/competencies/cycles/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/verify': typeof VerifyRoute
  '/admin': typeof AdminIndexRoute
  '/requests': typeof RequestsIndexRoute
  '/admin/teams/$teamId': typeof AdminTeamsTeamIdRoute
  '/admin/teams/analytics': typeof AdminTeamsAnalyticsRoute
  '/admin/competencies': typeof AdminCompetenciesIndexRoute
  '/admin/email-templates': typeof AdminEmailTemplatesIndexRoute
  '/admin/profile-requests': typeof AdminProfileRequestsIndexRoute
  '/admin/requests': typeof AdminRequestsIndexRoute
  '/admin/teams': typeof AdminTeamsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/competencies/cycles': typeof AdminCompetenciesCyclesIndexRoute
  '/admin/competencies/requirements': typeof AdminCompetenciesRequirementsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/verify': typeof VerifyRoute
  '/admin': typeof AdminIndexRoute
  '/requests': typeof RequestsIndexRoute
  '/admin/teams/$teamId': typeof AdminTeamsTeamIdRoute
  '/admin/teams/analytics': typeof AdminTeamsAnalyticsRoute
  '/admin/competencies': typeof AdminCompetenciesIndexRoute
  '/admin/email-templates': typeof AdminEmailTemplatesIndexRoute
  '/admin/profile-requests': typeof AdminProfileRequestsIndexRoute
  '/admin/requests': typeof AdminRequestsIndexRoute
  '/admin/teams': typeof AdminTeamsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/competencies/cycles': typeof AdminCompetenciesCyclesIndexRoute
  '/admin/competencies/requirements': typeof AdminCompetenciesRequirementsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/verify': typeof VerifyRoute
  '/admin/': typeof AdminIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/admin/teams/$teamId': typeof AdminTeamsTeamIdRoute
  '/admin/teams/analytics': typeof AdminTeamsAnalyticsRoute
  '/admin/competencies/': typeof AdminCompetenciesIndexRoute
  '/admin/email-templates/': typeof AdminEmailTemplatesIndexRoute
  '/admin/profile-requests/': typeof AdminProfileRequestsIndexRoute
  '/admin/requests/': typeof AdminRequestsIndexRoute
  '/admin/teams/': typeof AdminTeamsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/competencies/cycles/': typeof AdminCompetenciesCyclesIndexRoute
  '/admin/competencies/requirements/': typeof AdminCompetenciesRequirementsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/login'
    | '/profile'
    | '/verify'
    | '/admin'
    | '/requests'
    | '/admin/teams/$teamId'
    | '/admin/teams/analytics'
    | '/admin/competencies'
    | '/admin/email-templates'
    | '/admin/profile-requests'
    | '/admin/requests'
    | '/admin/teams'
    | '/admin/users'
    | '/admin/competencies/cycles'
    | '/admin/competencies/requirements'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/login'
    | '/profile'
    | '/verify'
    | '/admin'
    | '/requests'
    | '/admin/teams/$teamId'
    | '/admin/teams/analytics'
    | '/admin/competencies'
    | '/admin/email-templates'
    | '/admin/profile-requests'
    | '/admin/requests'
    | '/admin/teams'
    | '/admin/users'
    | '/admin/competencies/cycles'
    | '/admin/competencies/requirements'
  id:
    | '__root__'
    | '/'
    | '/change-password'
    | '/login'
    | '/profile'
    | '/verify'
    | '/admin/'
    | '/requests/'
    | '/admin/teams/$teamId'
    | '/admin/teams/analytics'
    | '/admin/competencies/'
    | '/admin/email-templates/'
    | '/admin/profile-requests/'
    | '/admin/requests/'
    | '/admin/teams/'
    | '/admin/users/'
    | '/admin/competencies/cycles/'
    | '/admin/competencies/requirements/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  VerifyRoute: typeof VerifyRoute
  AdminIndexRoute: typeof AdminIndexRoute
  RequestsIndexRoute: typeof RequestsIndexRoute
  AdminTeamsTeamIdRoute: typeof AdminTeamsTeamIdRoute
  AdminTeamsAnalyticsRoute: typeof AdminTeamsAnalyticsRoute
  AdminCompetenciesIndexRoute: typeof AdminCompetenciesIndexRoute
  AdminEmailTemplatesIndexRoute: typeof AdminEmailTemplatesIndexRoute
  AdminProfileRequestsIndexRoute: typeof AdminProfileRequestsIndexRoute
  AdminRequestsIndexRoute: typeof AdminRequestsIndexRoute
  AdminTeamsIndexRoute: typeof AdminTeamsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminCompetenciesCyclesIndexRoute: typeof AdminCompetenciesCyclesIndexRoute
  AdminCompetenciesRequirementsIndexRoute: typeof AdminCompetenciesRequirementsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/': {
      id: '/requests/'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teams/': {
      id: '/admin/teams/'
      path: '/admin/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminTeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/requests/': {
      id: '/admin/requests/'
      path: '/admin/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile-requests/': {
      id: '/admin/profile-requests/'
      path: '/admin/profile-requests'
      fullPath: '/admin/profile-requests'
      preLoaderRoute: typeof AdminProfileRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/email-templates/': {
      id: '/admin/email-templates/'
      path: '/admin/email-templates'
      fullPath: '/admin/email-templates'
      preLoaderRoute: typeof AdminEmailTemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/competencies/': {
      id: '/admin/competencies/'
      path: '/admin/competencies'
      fullPath: '/admin/competencies'
      preLoaderRoute: typeof AdminCompetenciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teams/analytics': {
      id: '/admin/teams/analytics'
      path: '/admin/teams/analytics'
      fullPath: '/admin/teams/analytics'
      preLoaderRoute: typeof AdminTeamsAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teams/$teamId': {
      id: '/admin/teams/$teamId'
      path: '/admin/teams/$teamId'
      fullPath: '/admin/teams/$teamId'
      preLoaderRoute: typeof AdminTeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/competencies/requirements/': {
      id: '/admin/competencies/requirements/'
      path: '/admin/competencies/requirements'
      fullPath: '/admin/competencies/requirements'
      preLoaderRoute: typeof AdminCompetenciesRequirementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/competencies/cycles/': {
      id: '/admin/competencies/cycles/'
      path: '/admin/competencies/cycles'
      fullPath: '/admin/competencies/cycles'
      preLoaderRoute: typeof AdminCompetenciesCyclesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  VerifyRoute: VerifyRoute,
  AdminIndexRoute: AdminIndexRoute,
  RequestsIndexRoute: RequestsIndexRoute,
  AdminTeamsTeamIdRoute: AdminTeamsTeamIdRoute,
  AdminTeamsAnalyticsRoute: AdminTeamsAnalyticsRoute,
  AdminCompetenciesIndexRoute: AdminCompetenciesIndexRoute,
  AdminEmailTemplatesIndexRoute: AdminEmailTemplatesIndexRoute,
  AdminProfileRequestsIndexRoute: AdminProfileRequestsIndexRoute,
  AdminRequestsIndexRoute: AdminRequestsIndexRoute,
  AdminTeamsIndexRoute: AdminTeamsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminCompetenciesCyclesIndexRoute: AdminCompetenciesCyclesIndexRoute,
  AdminCompetenciesRequirementsIndexRoute:
    AdminCompetenciesRequirementsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
