/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TimesheetIndexRouteImport } from './routes/timesheet/index'
import { Route as RequestsIndexRouteImport } from './routes/requests/index'
import { Route as MyCvIndexRouteImport } from './routes/my-cv/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TeamIdpIndexRouteImport } from './routes/team/idp/index'
import { Route as TeamAssessmentsIndexRouteImport } from './routes/team/assessments/index'
import { Route as CompetenciesMySkillsIndexRouteImport } from './routes/competencies/my-skills/index'
import { Route as CompetenciesMyAssessmentIndexRouteImport } from './routes/competencies/my-assessment/index'
import { Route as CompetenciesIdpIndexRouteImport } from './routes/competencies/idp/index'
import { Route as CompetenciesAssessmentsIndexRouteImport } from './routes/competencies/assessments/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminTeamsIndexRouteImport } from './routes/admin/teams/index'
import { Route as AdminRequestsIndexRouteImport } from './routes/admin/requests/index'
import { Route as AdminProfileRequestsIndexRouteImport } from './routes/admin/profile-requests/index'
import { Route as AdminEmailTemplatesIndexRouteImport } from './routes/admin/email-templates/index'
import { Route as AdminCompetenciesIndexRouteImport } from './routes/admin/competencies/index'
import { Route as TeamIdpIdpIdRouteImport } from './routes/team/idp/$idpId'
import { Route as TeamCompetenciesAnalyticsRouteImport } from './routes/team/competencies/analytics'
import { Route as CompetenciesResultsAssessmentIdRouteImport } from './routes/competencies/results/$assessmentId'
import { Route as CompetenciesIdpCreateRouteImport } from './routes/competencies/idp/create'
import { Route as CompetenciesAssessmentsAssessmentIdRouteImport } from './routes/competencies/assessments/$assessmentId'
import { Route as AdminTeamsAnalyticsRouteImport } from './routes/admin/teams/analytics'
import { Route as AdminTeamsTeamIdRouteImport } from './routes/admin/teams/$teamId'
import { Route as AdminCompetenciesAnalyticsRouteImport } from './routes/admin/competencies/analytics'
import { Route as AdminCompetenciesRequirementsIndexRouteImport } from './routes/admin/competencies/requirements/index'
import { Route as AdminCompetenciesCyclesIndexRouteImport } from './routes/admin/competencies/cycles/index'
import { Route as AdminCompetenciesCyclesCycleIdRouteImport } from './routes/admin/competencies/cycles/$cycleId'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimesheetIndexRoute = TimesheetIndexRouteImport.update({
  id: '/timesheet/',
  path: '/timesheet/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIndexRoute = RequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCvIndexRoute = MyCvIndexRouteImport.update({
  id: '/my-cv/',
  path: '/my-cv/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIdpIndexRoute = TeamIdpIndexRouteImport.update({
  id: '/team/idp/',
  path: '/team/idp/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamAssessmentsIndexRoute = TeamAssessmentsIndexRouteImport.update({
  id: '/team/assessments/',
  path: '/team/assessments/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetenciesMySkillsIndexRoute =
  CompetenciesMySkillsIndexRouteImport.update({
    id: '/competencies/my-skills/',
    path: '/competencies/my-skills/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompetenciesMyAssessmentIndexRoute =
  CompetenciesMyAssessmentIndexRouteImport.update({
    id: '/competencies/my-assessment/',
    path: '/competencies/my-assessment/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompetenciesIdpIndexRoute = CompetenciesIdpIndexRouteImport.update({
  id: '/competencies/idp/',
  path: '/competencies/idp/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetenciesAssessmentsIndexRoute =
  CompetenciesAssessmentsIndexRouteImport.update({
    id: '/competencies/assessments/',
    path: '/competencies/assessments/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamsIndexRoute = AdminTeamsIndexRouteImport.update({
  id: '/admin/teams/',
  path: '/admin/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRequestsIndexRoute = AdminRequestsIndexRouteImport.update({
  id: '/admin/requests/',
  path: '/admin/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRequestsIndexRoute =
  AdminProfileRequestsIndexRouteImport.update({
    id: '/admin/profile-requests/',
    path: '/admin/profile-requests/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminEmailTemplatesIndexRoute =
  AdminEmailTemplatesIndexRouteImport.update({
    id: '/admin/email-templates/',
    path: '/admin/email-templates/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCompetenciesIndexRoute = AdminCompetenciesIndexRouteImport.update({
  id: '/admin/competencies/',
  path: '/admin/competencies/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIdpIdpIdRoute = TeamIdpIdpIdRouteImport.update({
  id: '/team/idp/$idpId',
  path: '/team/idp/$idpId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamCompetenciesAnalyticsRoute =
  TeamCompetenciesAnalyticsRouteImport.update({
    id: '/team/competencies/analytics',
    path: '/team/competencies/analytics',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompetenciesResultsAssessmentIdRoute =
  CompetenciesResultsAssessmentIdRouteImport.update({
    id: '/competencies/results/$assessmentId',
    path: '/competencies/results/$assessmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompetenciesIdpCreateRoute = CompetenciesIdpCreateRouteImport.update({
  id: '/competencies/idp/create',
  path: '/competencies/idp/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetenciesAssessmentsAssessmentIdRoute =
  CompetenciesAssessmentsAssessmentIdRouteImport.update({
    id: '/competencies/assessments/$assessmentId',
    path: '/competencies/assessments/$assessmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminTeamsAnalyticsRoute = AdminTeamsAnalyticsRouteImport.update({
  id: '/admin/teams/analytics',
  path: '/admin/teams/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamsTeamIdRoute = AdminTeamsTeamIdRouteImport.update({
  id: '/admin/teams/$teamId',
  path: '/admin/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCompetenciesAnalyticsRoute =
  AdminCompetenciesAnalyticsRouteImport.update({
    id: '/admin/competencies/analytics',
    path: '/admin/competencies/analytics',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCompetenciesRequirementsIndexRoute =
  AdminCompetenciesRequirementsIndexRouteImport.update({
    id: '/admin/competencies/requirements/',
    path: '/admin/competencies/requirements/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCompetenciesCyclesIndexRoute =
  AdminCompetenciesCyclesIndexRouteImport.update({
    id: '/admin/competencies/cycles/',
    path: '/admin/competencies/cycles/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCompetenciesCyclesCycleIdRoute =
  AdminCompetenciesCyclesCycleIdRouteImport.update({
    id: '/admin/competencies/cycles/$cycleId',
    path: '/admin/competencies/cycles/$cycleId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/verify': typeof VerifyRoute
  '/admin': typeof AdminIndexRoute
  '/my-cv': typeof MyCvIndexRoute
  '/requests': typeof RequestsIndexRoute
  '/timesheet': typeof TimesheetIndexRoute
  '/admin/competencies/analytics': typeof AdminCompetenciesAnalyticsRoute
  '/admin/teams/$teamId': typeof AdminTeamsTeamIdRoute
  '/admin/teams/analytics': typeof AdminTeamsAnalyticsRoute
  '/competencies/assessments/$assessmentId': typeof CompetenciesAssessmentsAssessmentIdRoute
  '/competencies/idp/create': typeof CompetenciesIdpCreateRoute
  '/competencies/results/$assessmentId': typeof CompetenciesResultsAssessmentIdRoute
  '/team/competencies/analytics': typeof TeamCompetenciesAnalyticsRoute
  '/team/idp/$idpId': typeof TeamIdpIdpIdRoute
  '/admin/competencies': typeof AdminCompetenciesIndexRoute
  '/admin/email-templates': typeof AdminEmailTemplatesIndexRoute
  '/admin/profile-requests': typeof AdminProfileRequestsIndexRoute
  '/admin/requests': typeof AdminRequestsIndexRoute
  '/admin/teams': typeof AdminTeamsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/competencies/assessments': typeof CompetenciesAssessmentsIndexRoute
  '/competencies/idp': typeof CompetenciesIdpIndexRoute
  '/competencies/my-assessment': typeof CompetenciesMyAssessmentIndexRoute
  '/competencies/my-skills': typeof CompetenciesMySkillsIndexRoute
  '/team/assessments': typeof TeamAssessmentsIndexRoute
  '/team/idp': typeof TeamIdpIndexRoute
  '/admin/competencies/cycles/$cycleId': typeof AdminCompetenciesCyclesCycleIdRoute
  '/admin/competencies/cycles': typeof AdminCompetenciesCyclesIndexRoute
  '/admin/competencies/requirements': typeof AdminCompetenciesRequirementsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/verify': typeof VerifyRoute
  '/admin': typeof AdminIndexRoute
  '/my-cv': typeof MyCvIndexRoute
  '/requests': typeof RequestsIndexRoute
  '/timesheet': typeof TimesheetIndexRoute
  '/admin/competencies/analytics': typeof AdminCompetenciesAnalyticsRoute
  '/admin/teams/$teamId': typeof AdminTeamsTeamIdRoute
  '/admin/teams/analytics': typeof AdminTeamsAnalyticsRoute
  '/competencies/assessments/$assessmentId': typeof CompetenciesAssessmentsAssessmentIdRoute
  '/competencies/idp/create': typeof CompetenciesIdpCreateRoute
  '/competencies/results/$assessmentId': typeof CompetenciesResultsAssessmentIdRoute
  '/team/competencies/analytics': typeof TeamCompetenciesAnalyticsRoute
  '/team/idp/$idpId': typeof TeamIdpIdpIdRoute
  '/admin/competencies': typeof AdminCompetenciesIndexRoute
  '/admin/email-templates': typeof AdminEmailTemplatesIndexRoute
  '/admin/profile-requests': typeof AdminProfileRequestsIndexRoute
  '/admin/requests': typeof AdminRequestsIndexRoute
  '/admin/teams': typeof AdminTeamsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/competencies/assessments': typeof CompetenciesAssessmentsIndexRoute
  '/competencies/idp': typeof CompetenciesIdpIndexRoute
  '/competencies/my-assessment': typeof CompetenciesMyAssessmentIndexRoute
  '/competencies/my-skills': typeof CompetenciesMySkillsIndexRoute
  '/team/assessments': typeof TeamAssessmentsIndexRoute
  '/team/idp': typeof TeamIdpIndexRoute
  '/admin/competencies/cycles/$cycleId': typeof AdminCompetenciesCyclesCycleIdRoute
  '/admin/competencies/cycles': typeof AdminCompetenciesCyclesIndexRoute
  '/admin/competencies/requirements': typeof AdminCompetenciesRequirementsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/verify': typeof VerifyRoute
  '/admin/': typeof AdminIndexRoute
  '/my-cv/': typeof MyCvIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/timesheet/': typeof TimesheetIndexRoute
  '/admin/competencies/analytics': typeof AdminCompetenciesAnalyticsRoute
  '/admin/teams/$teamId': typeof AdminTeamsTeamIdRoute
  '/admin/teams/analytics': typeof AdminTeamsAnalyticsRoute
  '/competencies/assessments/$assessmentId': typeof CompetenciesAssessmentsAssessmentIdRoute
  '/competencies/idp/create': typeof CompetenciesIdpCreateRoute
  '/competencies/results/$assessmentId': typeof CompetenciesResultsAssessmentIdRoute
  '/team/competencies/analytics': typeof TeamCompetenciesAnalyticsRoute
  '/team/idp/$idpId': typeof TeamIdpIdpIdRoute
  '/admin/competencies/': typeof AdminCompetenciesIndexRoute
  '/admin/email-templates/': typeof AdminEmailTemplatesIndexRoute
  '/admin/profile-requests/': typeof AdminProfileRequestsIndexRoute
  '/admin/requests/': typeof AdminRequestsIndexRoute
  '/admin/teams/': typeof AdminTeamsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/competencies/assessments/': typeof CompetenciesAssessmentsIndexRoute
  '/competencies/idp/': typeof CompetenciesIdpIndexRoute
  '/competencies/my-assessment/': typeof CompetenciesMyAssessmentIndexRoute
  '/competencies/my-skills/': typeof CompetenciesMySkillsIndexRoute
  '/team/assessments/': typeof TeamAssessmentsIndexRoute
  '/team/idp/': typeof TeamIdpIndexRoute
  '/admin/competencies/cycles/$cycleId': typeof AdminCompetenciesCyclesCycleIdRoute
  '/admin/competencies/cycles/': typeof AdminCompetenciesCyclesIndexRoute
  '/admin/competencies/requirements/': typeof AdminCompetenciesRequirementsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/login'
    | '/profile'
    | '/verify'
    | '/admin'
    | '/my-cv'
    | '/requests'
    | '/timesheet'
    | '/admin/competencies/analytics'
    | '/admin/teams/$teamId'
    | '/admin/teams/analytics'
    | '/competencies/assessments/$assessmentId'
    | '/competencies/idp/create'
    | '/competencies/results/$assessmentId'
    | '/team/competencies/analytics'
    | '/team/idp/$idpId'
    | '/admin/competencies'
    | '/admin/email-templates'
    | '/admin/profile-requests'
    | '/admin/requests'
    | '/admin/teams'
    | '/admin/users'
    | '/competencies/assessments'
    | '/competencies/idp'
    | '/competencies/my-assessment'
    | '/competencies/my-skills'
    | '/team/assessments'
    | '/team/idp'
    | '/admin/competencies/cycles/$cycleId'
    | '/admin/competencies/cycles'
    | '/admin/competencies/requirements'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/login'
    | '/profile'
    | '/verify'
    | '/admin'
    | '/my-cv'
    | '/requests'
    | '/timesheet'
    | '/admin/competencies/analytics'
    | '/admin/teams/$teamId'
    | '/admin/teams/analytics'
    | '/competencies/assessments/$assessmentId'
    | '/competencies/idp/create'
    | '/competencies/results/$assessmentId'
    | '/team/competencies/analytics'
    | '/team/idp/$idpId'
    | '/admin/competencies'
    | '/admin/email-templates'
    | '/admin/profile-requests'
    | '/admin/requests'
    | '/admin/teams'
    | '/admin/users'
    | '/competencies/assessments'
    | '/competencies/idp'
    | '/competencies/my-assessment'
    | '/competencies/my-skills'
    | '/team/assessments'
    | '/team/idp'
    | '/admin/competencies/cycles/$cycleId'
    | '/admin/competencies/cycles'
    | '/admin/competencies/requirements'
  id:
    | '__root__'
    | '/'
    | '/change-password'
    | '/login'
    | '/profile'
    | '/verify'
    | '/admin/'
    | '/my-cv/'
    | '/requests/'
    | '/timesheet/'
    | '/admin/competencies/analytics'
    | '/admin/teams/$teamId'
    | '/admin/teams/analytics'
    | '/competencies/assessments/$assessmentId'
    | '/competencies/idp/create'
    | '/competencies/results/$assessmentId'
    | '/team/competencies/analytics'
    | '/team/idp/$idpId'
    | '/admin/competencies/'
    | '/admin/email-templates/'
    | '/admin/profile-requests/'
    | '/admin/requests/'
    | '/admin/teams/'
    | '/admin/users/'
    | '/competencies/assessments/'
    | '/competencies/idp/'
    | '/competencies/my-assessment/'
    | '/competencies/my-skills/'
    | '/team/assessments/'
    | '/team/idp/'
    | '/admin/competencies/cycles/$cycleId'
    | '/admin/competencies/cycles/'
    | '/admin/competencies/requirements/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  VerifyRoute: typeof VerifyRoute
  AdminIndexRoute: typeof AdminIndexRoute
  MyCvIndexRoute: typeof MyCvIndexRoute
  RequestsIndexRoute: typeof RequestsIndexRoute
  TimesheetIndexRoute: typeof TimesheetIndexRoute
  AdminCompetenciesAnalyticsRoute: typeof AdminCompetenciesAnalyticsRoute
  AdminTeamsTeamIdRoute: typeof AdminTeamsTeamIdRoute
  AdminTeamsAnalyticsRoute: typeof AdminTeamsAnalyticsRoute
  CompetenciesAssessmentsAssessmentIdRoute: typeof CompetenciesAssessmentsAssessmentIdRoute
  CompetenciesIdpCreateRoute: typeof CompetenciesIdpCreateRoute
  CompetenciesResultsAssessmentIdRoute: typeof CompetenciesResultsAssessmentIdRoute
  TeamCompetenciesAnalyticsRoute: typeof TeamCompetenciesAnalyticsRoute
  TeamIdpIdpIdRoute: typeof TeamIdpIdpIdRoute
  AdminCompetenciesIndexRoute: typeof AdminCompetenciesIndexRoute
  AdminEmailTemplatesIndexRoute: typeof AdminEmailTemplatesIndexRoute
  AdminProfileRequestsIndexRoute: typeof AdminProfileRequestsIndexRoute
  AdminRequestsIndexRoute: typeof AdminRequestsIndexRoute
  AdminTeamsIndexRoute: typeof AdminTeamsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  CompetenciesAssessmentsIndexRoute: typeof CompetenciesAssessmentsIndexRoute
  CompetenciesIdpIndexRoute: typeof CompetenciesIdpIndexRoute
  CompetenciesMyAssessmentIndexRoute: typeof CompetenciesMyAssessmentIndexRoute
  CompetenciesMySkillsIndexRoute: typeof CompetenciesMySkillsIndexRoute
  TeamAssessmentsIndexRoute: typeof TeamAssessmentsIndexRoute
  TeamIdpIndexRoute: typeof TeamIdpIndexRoute
  AdminCompetenciesCyclesCycleIdRoute: typeof AdminCompetenciesCyclesCycleIdRoute
  AdminCompetenciesCyclesIndexRoute: typeof AdminCompetenciesCyclesIndexRoute
  AdminCompetenciesRequirementsIndexRoute: typeof AdminCompetenciesRequirementsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timesheet/': {
      id: '/timesheet/'
      path: '/timesheet'
      fullPath: '/timesheet'
      preLoaderRoute: typeof TimesheetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/': {
      id: '/requests/'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-cv/': {
      id: '/my-cv/'
      path: '/my-cv'
      fullPath: '/my-cv'
      preLoaderRoute: typeof MyCvIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/idp/': {
      id: '/team/idp/'
      path: '/team/idp'
      fullPath: '/team/idp'
      preLoaderRoute: typeof TeamIdpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/assessments/': {
      id: '/team/assessments/'
      path: '/team/assessments'
      fullPath: '/team/assessments'
      preLoaderRoute: typeof TeamAssessmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competencies/my-skills/': {
      id: '/competencies/my-skills/'
      path: '/competencies/my-skills'
      fullPath: '/competencies/my-skills'
      preLoaderRoute: typeof CompetenciesMySkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competencies/my-assessment/': {
      id: '/competencies/my-assessment/'
      path: '/competencies/my-assessment'
      fullPath: '/competencies/my-assessment'
      preLoaderRoute: typeof CompetenciesMyAssessmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competencies/idp/': {
      id: '/competencies/idp/'
      path: '/competencies/idp'
      fullPath: '/competencies/idp'
      preLoaderRoute: typeof CompetenciesIdpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competencies/assessments/': {
      id: '/competencies/assessments/'
      path: '/competencies/assessments'
      fullPath: '/competencies/assessments'
      preLoaderRoute: typeof CompetenciesAssessmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teams/': {
      id: '/admin/teams/'
      path: '/admin/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminTeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/requests/': {
      id: '/admin/requests/'
      path: '/admin/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile-requests/': {
      id: '/admin/profile-requests/'
      path: '/admin/profile-requests'
      fullPath: '/admin/profile-requests'
      preLoaderRoute: typeof AdminProfileRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/email-templates/': {
      id: '/admin/email-templates/'
      path: '/admin/email-templates'
      fullPath: '/admin/email-templates'
      preLoaderRoute: typeof AdminEmailTemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/competencies/': {
      id: '/admin/competencies/'
      path: '/admin/competencies'
      fullPath: '/admin/competencies'
      preLoaderRoute: typeof AdminCompetenciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/idp/$idpId': {
      id: '/team/idp/$idpId'
      path: '/team/idp/$idpId'
      fullPath: '/team/idp/$idpId'
      preLoaderRoute: typeof TeamIdpIdpIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/competencies/analytics': {
      id: '/team/competencies/analytics'
      path: '/team/competencies/analytics'
      fullPath: '/team/competencies/analytics'
      preLoaderRoute: typeof TeamCompetenciesAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competencies/results/$assessmentId': {
      id: '/competencies/results/$assessmentId'
      path: '/competencies/results/$assessmentId'
      fullPath: '/competencies/results/$assessmentId'
      preLoaderRoute: typeof CompetenciesResultsAssessmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competencies/idp/create': {
      id: '/competencies/idp/create'
      path: '/competencies/idp/create'
      fullPath: '/competencies/idp/create'
      preLoaderRoute: typeof CompetenciesIdpCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competencies/assessments/$assessmentId': {
      id: '/competencies/assessments/$assessmentId'
      path: '/competencies/assessments/$assessmentId'
      fullPath: '/competencies/assessments/$assessmentId'
      preLoaderRoute: typeof CompetenciesAssessmentsAssessmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teams/analytics': {
      id: '/admin/teams/analytics'
      path: '/admin/teams/analytics'
      fullPath: '/admin/teams/analytics'
      preLoaderRoute: typeof AdminTeamsAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teams/$teamId': {
      id: '/admin/teams/$teamId'
      path: '/admin/teams/$teamId'
      fullPath: '/admin/teams/$teamId'
      preLoaderRoute: typeof AdminTeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/competencies/analytics': {
      id: '/admin/competencies/analytics'
      path: '/admin/competencies/analytics'
      fullPath: '/admin/competencies/analytics'
      preLoaderRoute: typeof AdminCompetenciesAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/competencies/requirements/': {
      id: '/admin/competencies/requirements/'
      path: '/admin/competencies/requirements'
      fullPath: '/admin/competencies/requirements'
      preLoaderRoute: typeof AdminCompetenciesRequirementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/competencies/cycles/': {
      id: '/admin/competencies/cycles/'
      path: '/admin/competencies/cycles'
      fullPath: '/admin/competencies/cycles'
      preLoaderRoute: typeof AdminCompetenciesCyclesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/competencies/cycles/$cycleId': {
      id: '/admin/competencies/cycles/$cycleId'
      path: '/admin/competencies/cycles/$cycleId'
      fullPath: '/admin/competencies/cycles/$cycleId'
      preLoaderRoute: typeof AdminCompetenciesCyclesCycleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  VerifyRoute: VerifyRoute,
  AdminIndexRoute: AdminIndexRoute,
  MyCvIndexRoute: MyCvIndexRoute,
  RequestsIndexRoute: RequestsIndexRoute,
  TimesheetIndexRoute: TimesheetIndexRoute,
  AdminCompetenciesAnalyticsRoute: AdminCompetenciesAnalyticsRoute,
  AdminTeamsTeamIdRoute: AdminTeamsTeamIdRoute,
  AdminTeamsAnalyticsRoute: AdminTeamsAnalyticsRoute,
  CompetenciesAssessmentsAssessmentIdRoute:
    CompetenciesAssessmentsAssessmentIdRoute,
  CompetenciesIdpCreateRoute: CompetenciesIdpCreateRoute,
  CompetenciesResultsAssessmentIdRoute: CompetenciesResultsAssessmentIdRoute,
  TeamCompetenciesAnalyticsRoute: TeamCompetenciesAnalyticsRoute,
  TeamIdpIdpIdRoute: TeamIdpIdpIdRoute,
  AdminCompetenciesIndexRoute: AdminCompetenciesIndexRoute,
  AdminEmailTemplatesIndexRoute: AdminEmailTemplatesIndexRoute,
  AdminProfileRequestsIndexRoute: AdminProfileRequestsIndexRoute,
  AdminRequestsIndexRoute: AdminRequestsIndexRoute,
  AdminTeamsIndexRoute: AdminTeamsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  CompetenciesAssessmentsIndexRoute: CompetenciesAssessmentsIndexRoute,
  CompetenciesIdpIndexRoute: CompetenciesIdpIndexRoute,
  CompetenciesMyAssessmentIndexRoute: CompetenciesMyAssessmentIndexRoute,
  CompetenciesMySkillsIndexRoute: CompetenciesMySkillsIndexRoute,
  TeamAssessmentsIndexRoute: TeamAssessmentsIndexRoute,
  TeamIdpIndexRoute: TeamIdpIndexRoute,
  AdminCompetenciesCyclesCycleIdRoute: AdminCompetenciesCyclesCycleIdRoute,
  AdminCompetenciesCyclesIndexRoute: AdminCompetenciesCyclesIndexRoute,
  AdminCompetenciesRequirementsIndexRoute:
    AdminCompetenciesRequirementsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
